title: Juan Salazar
description: ISS Robotics Analyst/Systems Engineer @ NASA JSC
theme: jekyll-theme-cayman
include: ['_pages']
home_url: https://juansala.github.io/
resume_url: https://juansala.github.io/media/Docs/JuanSalazar_resume.pdf
projects_url: https://juansala.github.io/projects
publications_url: https://juansala.github.io/publications
github_profile_url: https://github.com/juansala
youtube_channel_url: https://www.youtube.com/channel/UCVG7EtCr7W0Ols7TKDskAtw
contact_url: https://juansala.github.io/contact